import test from 'node:test';
import assert from 'node:assert/strict';
import { createRoom, mutate, view, ROLE_IDS, EVIL } from '../lib/game.mjs';
function started(){let s=createRoom('u0','Persona 0');for(let i=1;i<8;i++)s=mutate(s,'u'+i,'join',{name:'Persona '+i});for(let i=0;i<8;i++)s=mutate(s,'u'+i,'ready');s=mutate(s,'u0','start');s.players.forEach((p,i)=>p.role=ROLE_IDS[i]);return s;}
function propose(s,team=s.players.slice(0,[3,4,4,5,5][s.mission]).map(p=>p.id)){s=mutate(s,s.players[s.leader].userId,'propose',{team});return s;}
function votes(s,approve=true){for(const p of s.players)s=mutate(s,p.userId,'vote',{approve});return s;}
function quest(s,sabotages=[]){for(const id of s.team){const p=s.players.find(p=>p.id===id);s=mutate(s,p.userId,'quest',{sabotage:sabotages.includes(p.role)});}return s;}
test('Eight unique roles, exact factions and start conditions',()=>{const s=started();assert.equal(new Set(s.players.map(p=>p.role)).size,8);assert.equal(s.players.filter(p=>EVIL.includes(p.role)).length,3);assert.throws(()=>mutate(createRoom('u','A'),'u','start'));assert.throws(()=>mutate(s,'outsider','vote',{approve:true}));});
test('Merlin cannot see Mordred; Parsifal sees ambiguous pair only',()=>{const s=started();const merlin=view(s,'u0');assert.deepEqual(merlin.me.knowledge.map(k=>k.id),[s.players[1].id,s.players[4].id]);const percival=view(s,'u2');assert.deepEqual(percival.me.knowledge.map(k=>k.id),[s.players[0].id,s.players[1].id]);assert(percival.me.knowledge.every(k=>k.label==='Merlino oppure Morgana'));for(let i=0;i<8;i++){const v=view(s,'u'+i);assert(v.players.every(p=>p.role===null));assert(!JSON.stringify(v).includes('userId'));assert(!('questVotes' in v));}assert.equal(view(s,'u5').me.knowledge.length,0);assert.equal(view(s,'u3').me.knowledge.length,2);});
test('No vote leaks before all 8 vote; tie rejects',()=>{let s=propose(started());s=mutate(s,'u0','vote',{approve:true});assert.equal(view(s,'u1').myVote,null);assert.equal(view(s,'u1').history.length,0);assert.throws(()=>mutate(s,'u0','vote',{approve:false}));for(let i=1;i<8;i++)s=mutate(s,'u'+i,'vote',{approve:i<4});assert.equal(s.phase,'result');assert.equal(s.rejections,1);assert.equal(s.history[0].approved,false);assert.equal(Object.keys(view(s,'u3').history[0].votes).length,8);});
test('Only leader selects correct unique team, only team delivers cards, good cannot sabotage',()=>{let s=started();assert.throws(()=>mutate(s,'u1','propose',{team:[]}));assert.throws(()=>propose(s,[s.players[0].id,s.players[0].id,s.players[1].id]));s=votes(propose(s));assert.equal(s.phase,'quest');assert.throws(()=>mutate(s,'u0','quest',{sabotage:true}));assert.throws(()=>mutate(s,'u7','quest',{sabotage:false}));s=quest(s,['morgana']);assert.equal(s.quests[0].success,false);assert.deepEqual(s.questVotes,{});const next=mutate(s,'u0','advance');assert.equal(next.leader,1);assert.equal(next.mission,1);});
test('Fourth quest requires two sabotages',()=>{let s=started();s.mission=3;s=votes(propose(s));s=quest(s,['morgana']);assert.equal(s.quests[0].success,true);s=started();s.mission=3;s=quest(votes(propose(s)),['morgana','mordred']);assert.equal(s.quests[0].success,false);});
test('Five rejected teams give evil victory',()=>{let s=started();for(let i=0;i<5;i++){s=votes(propose(s),false);if(i<4)s=mutate(s,'u0','advance');}assert.equal(s.winner,'evil');assert.equal(s.phase,'finished');});
test('Three successes trigger only Assassin; wrong and correct target outcomes',()=>{let s=started();for(let i=0;i<3;i++){s=quest(votes(propose(s)));if(i<2)s=mutate(s,'u0','advance');}assert.equal(s.phase,'assassination');assert.throws(()=>mutate(s,'u0','assassinate',{target:s.players[2].id}));assert.throws(()=>mutate(s,'u4','assassinate',{target:s.players[1].id}));const good=mutate(s,'u4','assassinate',{target:s.players[2].id});assert.equal(good.winner,'good');const evil=mutate(s,'u4','assassinate',{target:s.players[0].id});assert.equal(evil.winner,'evil');assert(view(evil,'u7').players.every(p=>p.role));const rematch=mutate(evil,'u0','rematch');assert(rematch.players.every(p=>!p.ready&&!p.role));assert.equal(rematch.phase,'lobby');});
test('Three failed missions end game without assassination',()=>{let s=started();for(let i=0;i<3;i++){s=quest(votes(propose(s)),['morgana']);if(i<2)s=mutate(s,'u0','advance');}assert.equal(s.phase,'finished');assert.equal(s.winner,'evil');});
test('Wrong phase and non-host changes rejected, reconnect idempotent',()=>{const s=started();assert.throws(()=>mutate(s,'u2','start'));assert.throws(()=>mutate(s,'u0','leave'));assert.throws(()=>mutate(s,'u0','ready'));assert.throws(()=>mutate(s,'u0','rematch'));assert.throws(()=>mutate(s,'u1','advance'));assert.equal(mutate(s,'u0','join',{name:'Again'}).players.length,8);assert.throws(()=>mutate(s,'outside','join',{name:'Ninth'}));});
test('Table portraits are filtered for every role without distinguishing Parsifal candidates',()=>{
 const s=started();const portraits=user=>view(s,user).players.map(p=>p.portrait);
 assert.deepEqual(portraits('u0'),['merlin','morgana','unknown','unknown','assassin','unknown','unknown','unknown']);
 assert.deepEqual(portraits('u2'),['merlin-morgana','merlin-morgana','percival','unknown','unknown','unknown','unknown','unknown']);
 for(const i of [1,3,4]){const expected=ROLE_IDS.map(r=>EVIL.includes(r)?r:'unknown');assert.deepEqual(portraits('u'+i),expected);}
 for(const i of [5,6,7]){const expected=ROLE_IDS.map((r,j)=>j===i?r:'unknown');assert.deepEqual(portraits('u'+i),expected);}
 // Both candidate objects carry only the identical composite visual, never the true role.
 const pv=view(s,'u2');for(const i of [0,1])assert.equal(pv.players[i].role,null);
 // Lobby and rematches remain completely covered, even with stale roles in a stored state.
 s.phase='lobby';for(let i=0;i<8;i++)assert(portraits('u'+i).every(p=>p==='unknown'));
 s.phase='finished';assert.deepEqual(portraits('u5'),ROLE_IDS);
});
