'use client';
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { roles } from '../lib/catalogue';
type Player={id:string;name:string;ready:boolean;role:string|null;portrait?:string};
type Room={code:string;revision:number;phase:string;host:string;leader:string;mission:number;rejections:number;team:string[];teamSize:number;players:Player[];me:{id:string;role:string|null;evil:boolean;knowledge:{id:string;label:string}[]};submitted:string[];questSubmitted:string[];myVote:boolean|null;myQuestSubmitted:boolean;quests:{mission:number;success:boolean;fails:number;team:string[]}[];history:{mission:number;leader:string;team:string[];votes:Record<string,boolean>;approved:boolean}[];chat:{id:string;player:string;name:string;message:string}[];result:any;winner:string|null;reason:string|null;target:string|null};
type Role=typeof roles[number];
const titleOf=(id:string|null)=>roles.find(r=>r.id===id);
function Portrait({art,className=''}:{art:number;className?:string}){return <div className={'portrait '+className} style={{backgroundPosition:`${(art%4)*100/3}% ${art<4?0:100}%`}} aria-hidden="true"/>;}
const positions=[[24,23],[50,19],[76,23],[91,50],[76,77],[50,81],[24,77],[9,50]];
function Table({room,selection,onSelect,onRole}:{room:Room|null;selection:string[];onSelect:(id:string)=>void;onRole:(role:Role)=>void}){
 const people=room?room.players:Array.from({length:8},(_,i)=>({id:String(i),name:roles[i].name,ready:false,role:roles[i].id}));
 const selectable=!!room&&((room.phase==='proposal'&&room.leader===room.me.id)||(room.phase==='assassination'&&room.me.role==='assassin'));
 return <div className={'table-stage '+(!room?'exhibition':'')} aria-label={room?'Tavolo della partita':'Gli otto personaggi del club'}>
  <div className="oval-table"><div className="table-engraving"><span className="star">✦</span><span>IL CLUB DEI BUGIARDI</span></div>{room&&<div className="table-center"><span className="eyebrow">{room.phase==='lobby'?'IL TAVOLO TI ASPETTA':room.phase==='assassination'?'UN SOLO COLPO':`MISSIONE ${room.mission+1}`}</span><strong>{room.phase==='lobby'?`${room.players.length} / 8`:room.phase==='finished'?'SIPARIO.':room.phase==='proposal'?`${selection.length} / ${room.teamSize}`:room.phase==='vote'?`${room.submitted.length} / 8`:room.phase==='quest'?`${room.questSubmitted.length} / ${room.teamSize}`:'✦'}</strong><small>{room.phase==='lobby'?'maschere al tavolo':room.phase==='proposal'?'compagni selezionati':room.phase==='vote'?'voti sigillati':room.phase==='quest'?'carte consegnate':room.phase==='finished'?'Tutte le identità sono svelate.':'Il tavolo trattiene il fiato.'}</small></div>}</div>
  {Array.from({length:8},(_,i)=>{const p:Player|undefined=people[i],appearance=p?.portrait??p?.role??'unknown',role=titleOf(appearance);const selected=p&&selection.includes(p.id);const identityLabel=role?.name??(appearance==='merlin-morgana'?'Merlino oppure Morgana':'Identità sconosciuta');return <button key={i} className={`seat seat-${i} ${selected?'selected':''} ${!p?'empty-seat':''}`} style={{'--x':positions[i][0]+'%','--y':positions[i][1]+'%'} as CSSProperties} disabled={!!room&&(!p||!selectable)} onClick={()=>{if(!p)return;if(room)onSelect(p.id);else if(role)onRole(role);}} aria-label={p?`${p.name}${room?', '+identityLabel:''}${selected?', selezionato':''}`:'Posto libero'} aria-pressed={selectable?!!selected:undefined}>
   <span className="chair"/>{role?<Portrait art={role.art}/>:<div className={'portrait '+(appearance==='merlin-morgana'?'portrait-parsifal':'portrait-unknown')} aria-hidden="true"/>}
   <span className="name-tag">{p?p.name:'POSTO LIBERO'}{room&&p?.id===room.me.id?' · TU':''}</span>
   {room&&p&&<span className={'seat-tag '+(p.id===room.leader&&room.phase!=='lobby'?'leader-tag':'')}>{room.phase==='lobby'?(p.ready?'PRONTO':'IN ATTESA'):p.id===room.leader?'LEADER':selected?'IN SQUADRA':room.phase==='vote'&&room.submitted.includes(p.id)?'VOTO SIGILLATO':role?role.side==='evil'?'CATTIVO':'BUONO':''}</span>}
  </button>;})}
 </div>;
}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title}><div className="dialog-header"><span className="eyebrow">{title}</span><button className="icon-button" onClick={onClose} aria-label="Chiudi">×</button></div>{children}</dialog>;}
export default function Club({signedIn,guestAccess=false}:{signedIn:boolean;guestAccess?:boolean}){
 const [room,setRoom]=useState<Room|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[mode,setMode]=useState<'create'|'join'>('create'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selection,setSelection]=useState<string[]>([]),[modal,setModal]=useState<'rules'|'roles'|'secret'|null>(null),[role,setRole]=useState<Role|null>(null),[chat,setChat]=useState(''),[panel,setPanel]=useState<'history'|'chat'>('history'),[connected,setConnected]=useState(true),[loaded,setLoaded]=useState(false),[invite,setInvite]=useState('');
 const revision=useRef(-1);const requestInFlight=useRef(false);const codeRef=useRef<string|null>(null);
 const accept=(next:Room)=>{if(codeRef.current===next.code&&next.revision<revision.current)return;codeRef.current=next.code;revision.current=next.revision;setRoom(next);setConnected(true);localStorage.setItem('avalon-room',next.code);};
 useEffect(()=>{setName(localStorage.getItem('avalon-name')||'');const q=new URLSearchParams(location.search).get('room');if(q){setCode(q.toUpperCase());setMode('join');setInvite(q.toUpperCase());}const saved=localStorage.getItem('avalon-room');if(saved&&signedIn){fetch('/api/room?code='+encodeURIComponent(saved),{cache:'no-store'}).then(r=>r.json() as Promise<Room & {error?:string}>).then(d=>{if(d.error){localStorage.removeItem('avalon-room');return;}accept(d);}).catch(()=>setError('Connessione non disponibile. Puoi riprovare a entrare nella stanza.')).finally(()=>setLoaded(true));}else setLoaded(true);},[signedIn]);
 useEffect(()=>{if(!room?.code)return;const c=room.code;let alive=true,fetching=false;const refresh=async()=>{if(fetching||document.hidden)return;fetching=true;try{const r=await fetch('/api/room?code='+encodeURIComponent(c),{cache:'no-store'});const d=await r.json() as Room & {error?:string;left?:boolean};if(!alive||codeRef.current!==c)return;if(d.error){setConnected(false);setError(d.error);}else accept(d);}catch{if(alive)setConnected(false);}finally{fetching=false;}};const id=setInterval(refresh,2200);window.addEventListener('focus',refresh);return()=>{alive=false;clearInterval(id);window.removeEventListener('focus',refresh);};},[room?.code]);
 useEffect(()=>{setSelection(room?.team??[]);setModal(null);},[room?.phase,room?.mission,room?.leader]);
 useEffect(()=>{const hide=()=>{if(document.hidden)setModal(m=>m==='secret'?null:m);};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
 async function act(action:string,data:Record<string,unknown>={}){if(requestInFlight.current)return;requestInFlight.current=true;setBusy(true);setError('');try{const r=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,code:room?.code||code,...data})});const d=await r.json() as Room & {error?:string;left?:boolean};if(d.error)throw new Error(d.error);if(d.left){setRoom(null);codeRef.current=null;revision.current=-1;localStorage.removeItem('avalon-room');}else accept(d);if(action==='chat')setChat('');return true;}catch(e){setError((e as Error).message);return false;}finally{requestInFlight.current=false;setBusy(false);}}
 function goHome(){if(room){setCode(room.code);setMode('join');}setRoom(null);codeRef.current=null;revision.current=-1;localStorage.removeItem('avalon-room');setModal(null);setRole(null);}
 function select(id:string){if(!room)return;if(room.phase==='assassination'){setSelection([id]);return;}setSelection(s=>s.includes(id)?s.filter(x=>x!==id):s.length<room.teamSize?[...s,id]:s);}
 const playerName=(id:string)=>room?.players.find(p=>p.id===id)?.name||'Giocatore';
 const myRole=titleOf(room?.me.role??null),isHost=room?.host===room?.me.id,isLeader=room?.leader===room?.me.id;
 const phaseTitles:Record<string,string>={lobby:'C’È UN POSTO\nPER TE.',proposal:isLeader?'DI CHI\nTI FIDI?':`${room?playerName(room.leader).toUpperCase():''}\nSTA SCEGLIENDO.`,vote:`${room?playerName(room.leader).toUpperCase():''}\nSI FIDA DI LORO.`,quest:'LE PROMESSE\nNON BASTANO.',result:room?.result?.kind==='rejected'?'FIDUCIA\nNEGATA.':room?.result?.success?'LA PAROLA\nÈ STATA DATA.':'QUALCUNO\nHA TRADITO.',assassination:'L’ULTIMA\nBUGIA.',finished:room?.winner==='good'?'MERLINO\nÈ SALVO.':'VINCONO\nLE OMBRE.'};
 async function copyInvite(){if(!room)return;try{await navigator.clipboard.writeText(location.origin+'/?room='+room.code);setNotice('Link d’invito copiato.');}catch{setNotice('Codice da condividere: '+room.code);}setTimeout(()=>setNotice(''),5000);}
 return <main>
 <header className="masthead"><a className="wordmark" href="/" onClick={e=>{e.preventDefault();goHome();}} aria-label="Avalon, pagina iniziale">AVALON<span>✦</span></a><span className="club-name">IL CLUB DEI BUGIARDI</span><nav>{room&&<button className="home-button" disabled={busy} onClick={goHome}>← Home</button>}<button className="masquerade-nav" onClick={()=>setModal('roles')}>Le maschere</button><button onClick={()=>setModal('rules')}>Come si gioca <span>↗</span></button></nav></header>
 {!room?<>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="red-dot"/> UN GIOCO DI FIDUCIA. O QUASI.</div><h1>QUI NESSUNO<br/>È <em>INNOCENTE.</em></h1><p>Otto maschere. Cinque leali. Tre traditori.<br/>Siediti al tavolo. Scegli di chi fidarti.</p><div className="hero-meta"><span>08 GIOCATORI</span><span>30–45 MIN</span><span>ONLINE</span></div></div>
  <form className="entry-card" onSubmit={async e=>{e.preventDefault();localStorage.setItem('avalon-name',name);await act(mode,{name,code});}}><div className="entry-heading"><span className="eyebrow">IL TUO POSTO AL TAVOLO</span><span>↙</span></div><div className="entry-tabs"><button type="button" aria-pressed={mode==='create'} onClick={()=>setMode('create')}>Crea stanza</button><button type="button" aria-pressed={mode==='join'} onClick={()=>setMode('join')}>Inserisci codice</button></div><label>COME TI CHIAMI?<input maxLength={22} value={name} onChange={e=>setName(e.target.value)} placeholder="Il nome con cui mentirai" autoComplete="nickname" required/></label>{mode==='join'&&<label>CODICE DELLA STANZA<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ES. K7M2AX" maxLength={6} minLength={6} required/></label>}{signedIn?<button className="primary" disabled={busy||!loaded}>{busy?'Un istante…':mode==='create'?'CREA STANZA':'ENTRA NELLA STANZA'} <span>↗</span></button>:<a className="primary" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(invite?'/?room='+invite:'/')} target="_top" onClick={()=>localStorage.setItem('avalon-name',name)}>ACCEDI E PRENDI POSTO <span>↗</span></a>}<p className="entry-note">Ogni giocatore entra dal proprio dispositivo.<br/>{guestAccess?'Accesso ospite: ritrovi il tuo posto usando lo stesso browser.':signedIn?'Invita gli altri sette con il codice della stanza.':'Accedi con ChatGPT per creare o raggiungere una stanza.'}</p></form></section>
  <section className="showcase"><div className="section-label"><span>OTTO IDENTITÀ. NESSUNA CERTEZZA.</span><span>ESPLORA LE MASCHERE ↓</span></div><Table room={null} selection={[]} onSelect={()=>{}} onRole={setRole}/><div className="showcase-caption"><span>LA SOCIETÀ AL COMPLETO</span><p>Al tavolo vedi il tuo personaggio<br/>e soltanto ciò che il tuo ruolo ti rivela.</p><span className="caption-star">✦</span></div></section>
  <section className="how-strip"><article><span>01 / OSSERVA</span><h2>Tutti hanno<br/>qualcosa da nascondere.</h2><p>Ricevi una maschera e le informazioni che soltanto il tuo ruolo può conoscere.</p></article><article><span>02 / SCEGLI</span><h2>La fiducia<br/>si mette ai voti.</h2><p>Proponi una squadra, discuti al tavolo e vota. Ogni scelta lascia una traccia.</p></article><article><span>03 / SOPRAVVIVI</span><h2>Anche vincere<br/>può essere una trappola.</h2><p>Tre missioni riuscite non bastano: Merlino deve sfuggire all’ultimo colpo.</p></article></section>
 </>:<>
 <div className="room-line"><span><i className={'status-dot '+(!connected?'offline':'')}/>{connected?'AL TAVOLO':'RICONNESSIONE…'}</span><button className="room-code" onClick={copyInvite}>STANZA <b>{room.code}</b> <span>↗ INVITA</span></button><span>{room.players.length}/8 PRESENTI</span></div>
 <section className="game-heading"><div><span className="eyebrow">{room.phase==='lobby'?'PRIMA CHE COMINCINO LE BUGIE':`MISSIONE ${room.mission+1} / ${({proposal:'PROPOSTA',vote:'VOTO',quest:'MISSIONE',result:'VERDETTO',assassination:'ASSASSINIO',finished:'FINE PARTITA'} as Record<string,string>)[room.phase]}`}</span><h1>{phaseTitles[room.phase].split('\n').map((s,i)=><span key={i}>{s}<br/></span>)}</h1></div><div className="quest-tracker"><div className="quests">{[3,4,4,5,5].map((size,i)=>{const q=room.quests.find(q=>q.mission===i);return <div key={i}><span>0{i+1}</span><div className={`quest ${q?q.success?'success':'failed':room.mission===i&&room.phase!=='lobby'?'current':''}`}>{q?q.success?'✓':'×':size}</div><small>{size} PERSONE{i===3?' *':''}</small></div>;})}</div><p>{room.quests.filter(q=>q.success).length} SUCCESSI / {room.quests.filter(q=>!q.success).length} FALLIMENTI</p><small>* Quarta missione: servono 2 sabotaggi.</small></div></section>
 <Table room={room} selection={selection} onSelect={select} onRole={setRole}/>
 <section className="action-bar"><div className="action-context"><span className="eyebrow">{room.phase==='lobby'?'LA SOCIETÀ SI RIUNISCE':room.phase==='vote'?'TI FIDI DI QUESTA SQUADRA?':room.phase==='quest'?'LA TUA CARTA RESTA SEGRETA':'LA PROSSIMA MOSSA'}</span><h2>{room.phase==='lobby'?`${room.players.filter(p=>p.ready).length} di 8 pronti`:room.phase==='proposal'?isLeader?`Scegli ${room.teamSize} compagni.`:'Aspetta la proposta del leader.':room.phase==='vote'?room.team.map(playerName).join(', '):room.phase==='quest'?room.team.includes(room.me.id)?'È il momento della verità.':'La squadra è in missione.':room.phase==='result'?room.result.kind==='rejected'?`${room.rejections} squadre rifiutate su 5.`:`${room.result.fails} carte Sabotaggio.`:room.phase==='assassination'?room.me.role==='assassin'?'Chi si nasconde dietro Merlino?':'L’Assassino sta scegliendo.':room.reason}</h2></div>
 <div className="actions">{room.phase==='lobby'&&<><button disabled={busy} onClick={()=>act('ready')}>{room.players.find(p=>p.id===room.me.id)?.ready?'NON SONO PRONTO':'SONO PRONTO'}</button>{isHost&&<button className="primary" disabled={busy||room.players.length!==8||room.players.some(p=>!p.ready)} onClick={()=>act('start')}>INIZIA PARTITA ↗</button>}</>}
 {room.phase==='proposal'&&isLeader&&<button className="primary" disabled={busy||selection.length!==room.teamSize} onClick={()=>act('propose',{team:selection})}>PROPONI SQUADRA · {selection.length}/{room.teamSize} ↗</button>}
 {room.phase==='vote'&&(room.submitted.includes(room.me.id)?<span className="sealed">✦ VOTO SIGILLATO · {room.submitted.length}/8</span>:<><button disabled={busy} onClick={()=>act('vote',{approve:false})}>RIFIUTO</button><button className="primary" disabled={busy} onClick={()=>act('vote',{approve:true})}>FIDUCIA</button></>)}
 {room.phase==='quest'&&room.team.includes(room.me.id)&&(room.myQuestSubmitted?<span className="sealed">✦ CARTA CONSEGNATA</span>:<><button className="primary" disabled={busy} onClick={()=>act('quest',{sabotage:false})}>SUCCESSO</button>{room.me.evil&&<button disabled={busy} onClick={()=>act('quest',{sabotage:true})}>SABOTAGGIO</button>}</>)}
 {room.phase==='result'&&(isHost?<button className="primary" disabled={busy} onClick={()=>act('advance')}>CONTINUA ↗</button>:<span className="sealed">IN ATTESA DELL’OSPITE</span>)}
 {room.phase==='assassination'&&room.me.role==='assassin'&&<button className="primary" disabled={busy||selection.length!==1||selection[0]===room.me.id||room.me.knowledge.some(k=>k.id===selection[0])} onClick={()=>{if(confirm(`Un solo colpo. Vuoi indicare ${playerName(selection[0])} come Merlino?`))act('assassinate',{target:selection[0]});}}>INDICA MERLINO ↗</button>}
 {room.phase==='finished'&&isHost&&<button className="primary" disabled={busy} onClick={()=>act('rematch')}>UN’ALTRA PARTITA ↗</button>}
 </div></section>
 <section className="room-bottom"><button className="secret-card" disabled={!myRole} onClick={()=>setModal('secret')}><span className="secret-symbol">◈</span><span>IL TUO SEGRETO<small>{myRole?'TOCCA PER RIVELARE':'IL RUOLO ARRIVERÀ ALL’INIZIO'}</small></span><span>↗</span></button><div className="log"><div className="log-tabs"><button aria-pressed={panel==='history'} onClick={()=>setPanel('history')}>IL VERBALE</button><button aria-pressed={panel==='chat'} onClick={()=>setPanel('chat')}>VOCI AL TAVOLO · {room.chat.length}</button></div>{panel==='history'?<div className="history">{!room.history.length?<p className="muted">Le promesse sono ancora tutte da verificare.</p>:room.history.slice().reverse().map((h,i)=><details key={room.history.length-i}><summary><span>MISSIONE {h.mission+1} · {playerName(h.leader)}</span><strong className={h.approved?'':'red'}>{h.approved?'APPROVATA':'RIFIUTATA'} ↓</strong></summary><p>Squadra: {h.team.map(playerName).join(', ')}</p><div className="vote-grid">{room.players.map(p=><span key={p.id}>{p.name}<b className={h.votes[p.id]?'':'red'}>{h.votes[p.id]?'SÌ':'NO'}</b></span>)}</div></details>)}</div>:<><div className="chat-messages" aria-live="polite">{!room.chat.length?<p className="muted">Rompi il silenzio. Tutti al tavolo leggono questi messaggi.</p>:room.chat.map(m=><p key={m.id}><strong>{m.name}</strong> {m.message}</p>)}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();act('chat',{message:chat});}}><input aria-label="Messaggio al tavolo" placeholder="Hai qualcosa da dichiarare?" maxLength={300} value={chat} onChange={e=>setChat(e.target.value)}/><button disabled={busy||!chat.trim()} aria-label="Invia messaggio">↗</button></form></>}</div></section>
 {room.phase==='lobby'&&<button className="leave" disabled={busy} onClick={()=>act('leave')}>Lascia il tavolo</button>}
 </>}
 {error&&<div className="notification error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Chiudi errore">×</button></div>}{notice&&<div className="notification" role="status">{notice}</div>}
 <footer className="site-footer"><span>AVALON <b>✦</b> IL CLUB DEI BUGIARDI</span><span>LA FIDUCIA È UNA SCELTA.</span><button onClick={()=>setModal('rules')}>Regole del tavolo ↗</button></footer>
 {modal==='rules'&&<Modal title="LE REGOLE DEL TAVOLO" onClose={()=>setModal(null)}><div className="rules"><h2>OTTO PERSONE.<br/>DUE FAZIONI.</h2><p>Merlino, Parsifal e i tre leali giocano per i buoni. Morgana, Mordred e l’Assassino giocano per i cattivi. Le identità vengono assegnate casualmente all’inizio.</p><ol><li><b>La proposta.</b> Il leader sceglie una squadra: 3, 4, 4, 5 e 5 persone nelle cinque missioni. La guida passa al giocatore successivo dopo ogni proposta rifiutata o missione conclusa.</li><li><b>Il voto.</b> Tutti votano Fiducia o Rifiuto. Servono almeno 5 sì. I voti si rivelano insieme; cinque proposte rifiutate nella stessa missione fanno vincere i cattivi.</li><li><b>La missione.</b> Ogni partecipante consegna una carta. I buoni devono scegliere Successo; i cattivi possono scegliere anche Sabotaggio. Basta un sabotaggio per fallire, tranne nella quarta missione: ne servono due. Si pubblica il totale, mai chi ha sabotato.</li><li><b>L’ultima bugia.</b> Tre fallimenti fanno vincere i cattivi. Dopo tre successi, l’Assassino tenta di identificare Merlino: se ci riesce vincono i cattivi, altrimenti i buoni.</li></ol><p className="muted">Parlate nella chat del tavolo o nella vostra chiamata vocale. Le stanze scadono dopo 48 ore senza azioni.</p><a href="https://www.rulespal.com/resistance-avalon/rulebook" target="_blank" rel="noreferrer">Consulta il regolamento di riferimento ↗</a></div></Modal>}
 {modal==='roles'&&<Modal title="LE OTTO MASCHERE" onClose={()=>setModal(null)}><div className="role-grid">{roles.map(r=><button key={r.id} onClick={()=>{setModal(null);setRole(r);}}><Portrait art={r.art}/><span className="eyebrow">{r.side==='good'?'LEALE':'TRADITORE'}</span><h3>{r.name}</h3><p>{r.mask}</p></button>)}</div></Modal>}
 {role&&<Modal title="IL PERSONAGGIO" onClose={()=>setRole(null)}><div className="role-detail"><Portrait art={role.art}/><div><span className="eyebrow red">{role.side==='good'?'DALLA PARTE DEI BUONI':'DALLA PARTE DEI CATTIVI'}</span><h2>{role.name}</h2><h3>{role.mask}</h3><p>{role.description}</p><button className="primary" onClick={()=>setRole(null)}>TORNA AL TAVOLO ↗</button></div></div></Modal>}
 {modal==='secret'&&room&&myRole&&<Modal title="SOLO PER I TUOI OCCHI" onClose={()=>setModal(null)}><div className="role-detail"><Portrait art={myRole.art}/><div><span className="eyebrow red">SEI {room.me.evil?'UN TRADITORE':'DALLA PARTE DEI BUONI'}</span><h2>{myRole.name}</h2><p>{myRole.description}</p><div className="knowledge"><span className="eyebrow">CIÒ CHE SAI</span>{room.me.knowledge.length?room.me.knowledge.map(k=><p key={k.id}><b>{playerName(k.id)}</b><span>{k.label}</span></p>):<p>Nessuna identità rivelata. Ascolta il tavolo.</p>}</div><button className="primary" onClick={()=>setModal(null)}>NASCONDI IL SEGRETO ↗</button></div></div></Modal>}
 </main>;
}

